### PR TITLE
Some symmetry and type fixes

### PR DESCRIPTION
**Pull request by KaffinPX**

### CODE REVIEW

**Comment by KaffinPX** [comment]
@IgorKhomenko this PR has a proper fix for "The address is invalid" error, can you please test?

**Comment by aspect** [comment]
Ok, I suppose changing `IUtxoEntry` to `UtxoEntry` reference is fine, I was trying to make it visible as `IUtxoEntry` as some functions intake this (like `GeneratorSettings::priorityEntries`) but I will update it via a commit once this is merged.

**Comment by DaveLomber** [comment]
@KaffinPX that seems to be working well 👍

**Comment by IgorKhomenko** [comment]
@KaffinPX I can confirm it fixes the issue 👍

**Pull request merged**
